"""Generate `docs/reference/*.md` from each module's `__all__`.

Run from the repo root before `mkdocs build`:

    uv run python docs/gen_ref_pages.py

For every top-level cairn package or single-file module listed in
`REFERENCE_MODULES`:

  1. Parse `__all__` from the package's `__init__.py` (or the module
     file itself for single-file bricks).
  2. Scan the source text for `# Section` comments interleaved in the
     `__all__` list — those become H2 headings.
  3. Write `docs/reference/<name>.md` with one `:::` mkdocstrings
     directive per symbol, in source order, grouped by section.

A short `docs/reference/index.md` is regenerated alongside.

Contract: every module listed must export `__all__`. A missing one
raises — the generator won't silently under-document.

CI integration: `--check` exits non-zero if any generated file
differs from what's checked in. That's the drift detector — the
nav lives in `mkdocs.yml`, but the per-module reference pages are
authored here.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path
from typing import NamedTuple

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_ROOT = REPO_ROOT / "src" / "cairn"
OUT_ROOT = REPO_ROOT / "docs" / "reference"

REFERENCE_MODULES: list[tuple[str, str]] = [
    ("config", "Config"),
    ("domain", "Domain"),
    ("logging", "Logging"),
    ("orchestrator", "Orchestrator"),
    ("persistence", "Persistence"),
    ("providers", "Providers"),
    ("ssl", "SSL"),
    ("tools", "Tools"),
]

GENERATED_BANNER = (
    "<!-- Generated by docs/gen_ref_pages.py from src/cairn/<module>/__init__.py.\n"
    "     Do not edit by hand — re-run the generator instead. -->\n"
)


class Section(NamedTuple):
    heading: str | None
    symbols: list[str]


def _source_path(name: str) -> Path:
    pkg = SRC_ROOT / name / "__init__.py"
    if pkg.exists():
        return pkg
    mod = SRC_ROOT / f"{name}.py"
    if mod.exists():
        return mod
    raise FileNotFoundError(f"No package or module found for cairn.{name}")


def _parse_all(source: str, path: Path) -> list[str]:
    tree = ast.parse(source, filename=str(path))
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
            if isinstance(target, ast.Name) and target.id == "__all__":
                value = node.value
                if not isinstance(value, ast.List | ast.Tuple):
                    raise ValueError(f"{path}: __all__ must be a list or tuple literal")
                names: list[str] = []
                for elt in value.elts:
                    if not isinstance(elt, ast.Constant) or not isinstance(elt.value, str):
                        raise ValueError(f"{path}: __all__ must contain string literals only")
                    names.append(elt.value)
                return names
    raise ValueError(f"{path}: missing __all__ — required for auto-reference")


_ALL_START_RE = re.compile(r"^__all__\s*=\s*[\[(]")
_ALL_END_RE = re.compile(r"^[\])]")
_SECTION_RE = re.compile(r"^\s*#\s*(.+?)\s*$")
_SYMBOL_RE = re.compile(r"^\s*[\"']([^\"']+)[\"']\s*,?\s*$")


def _parse_sections(source: str, known: list[str]) -> list[Section]:
    """Walk the __all__ block line by line; group symbols by `# Section` comments."""

    in_block = False
    current_heading: str | None = None
    buckets: list[Section] = []
    current: list[str] = []

    for line in source.splitlines():
        if not in_block:
            if _ALL_START_RE.match(line):
                in_block = True
            continue
        if _ALL_END_RE.match(line):
            break
        section_match = _SECTION_RE.match(line)
        if section_match:
            if current:
                buckets.append(Section(current_heading, current))
                current = []
            current_heading = section_match.group(1)
            continue
        symbol_match = _SYMBOL_RE.match(line)
        if symbol_match and symbol_match.group(1) in known:
            current.append(symbol_match.group(1))

    if current:
        buckets.append(Section(current_heading, current))

    if not buckets:
        buckets = [Section(None, list(known))]

    return buckets


def _render_module(name: str, display: str, sections: list[Section]) -> str:
    lines: list[str] = [GENERATED_BANNER, f"# {display} — API reference", ""]
    for section in sections:
        if section.heading:
            lines.append(f"## {section.heading}")
            lines.append("")
        for symbol in section.symbols:
            lines.append(f"::: cairn.{name}.{symbol}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _render_index() -> str:
    lines: list[str] = [
        GENERATED_BANNER,
        "# API reference",
        "",
        "Auto-generated from each package's `__all__`. Pages are grouped by",
        "the `# Section` comments inside `__all__`, so editorial structure",
        "lives next to the code rather than in hand-curated reference pages.",
        "",
        "Contributors: see `docs/gen_ref_pages.py` and `AGENTS.md` for the",
        "regeneration workflow.",
        "",
        "## Modules",
        "",
    ]
    for name, display in REFERENCE_MODULES:
        lines.append(f"- [{display}]({name}.md) — `cairn.{name}`")
    lines.append("")
    return "\n".join(lines)


def _build() -> dict[Path, str]:
    artefacts: dict[Path, str] = {}
    for name, display in REFERENCE_MODULES:
        path = _source_path(name)
        source = path.read_text(encoding="utf-8")
        names = _parse_all(source, path)
        sections = _parse_sections(source, names)
        artefacts[OUT_ROOT / f"{name}.md"] = _render_module(name, display, sections)
    artefacts[OUT_ROOT / "index.md"] = _render_index()
    return artefacts


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate docs/reference/*.md from __all__.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any file would change. Use in CI to detect drift.",
    )
    args = parser.parse_args(argv)

    artefacts = _build()
    OUT_ROOT.mkdir(parents=True, exist_ok=True)

    drift: list[Path] = []
    for out_path, content in artefacts.items():
        existing = out_path.read_text(encoding="utf-8") if out_path.exists() else None
        if existing == content:
            continue
        if args.check:
            drift.append(out_path)
        else:
            out_path.write_text(content, encoding="utf-8")

    if args.check:
        if drift:
            print("Reference docs are out of date. Re-run: uv run python docs/gen_ref_pages.py")
            for path in drift:
                print(f"  - {path.relative_to(REPO_ROOT)}")
            return 1
        return 0

    print(f"Wrote {len(artefacts)} reference pages under {OUT_ROOT.relative_to(REPO_ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
