"""Cairn domain layer — core data types for messages, sessions, and events."""

from cairn.domain._content import (
    ContentBlock,
    ImageBlock,
    ImageSource,
    TextBlock,
    ThinkingBlock,
    ToolResultBlock,
    ToolUseBlock,
    content_list_adapter,
)
from cairn.domain._enums import (
    ErrorClass,
    MemoryClass,
    MemoryEntryType,
    SessionType,
    StopReason,
    ToolCallStatus,
    UsageOperation,
)
from cairn.domain._events import (
    AssistantMessageComplete,
    AssistantTextDelta,
    AssistantThinkingDelta,
    BudgetOverflowAdvisory,
    BudgetWarning,
    ConfigDriftDetected,
    DelegationCompleted,
    DelegationSpawned,
    DriftChange,
    HistoryCompacted,
    ObservationExtractionCompleted,
    ObservationExtractionRequested,
    SessionArchived,
    SessionCreated,
    SessionResumed,
    ToolCallApproved,
    ToolCallCompleted,
    ToolCallPlanned,
    ToolCallRejected,
    ToolCallStarted,
    TurnAborted,
    TurnBlocked,
    TurnComplete,
    TurnIncomplete,
    UIEvent,
    UserMessagePersisted,
)
from cairn.domain._memory import MemoryEntry
from cairn.domain._messages import Message
from cairn.domain._provider import (
    MessageStop,
    ProviderEvent,
    ProviderRequest,
    SystemPromptSegment,
    TextDelta,
    ThinkingDelta,
    ToolCallDelta,
    ToolCallEnd,
    ToolCallStart,
    ToolDefinition,
    UsageEvent,
)
from cairn.domain._sessions import Session

__all__ = [
    # Content blocks
    "ContentBlock",
    "ImageBlock",
    "ImageSource",
    "TextBlock",
    "ThinkingBlock",
    "ToolResultBlock",
    "ToolUseBlock",
    "content_list_adapter",
    # Enums
    "ErrorClass",
    "MemoryClass",
    "MemoryEntryType",
    "SessionType",
    "StopReason",
    "ToolCallStatus",
    "UsageOperation",
    # UI events
    "AssistantMessageComplete",
    "AssistantTextDelta",
    "AssistantThinkingDelta",
    "BudgetOverflowAdvisory",
    "BudgetWarning",
    "ConfigDriftDetected",
    "DelegationCompleted",
    "DelegationSpawned",
    "DriftChange",
    "HistoryCompacted",
    "ObservationExtractionCompleted",
    "ObservationExtractionRequested",
    "SessionArchived",
    "SessionCreated",
    "SessionResumed",
    "ToolCallApproved",
    "ToolCallCompleted",
    "ToolCallPlanned",
    "ToolCallRejected",
    "ToolCallStarted",
    "TurnAborted",
    "TurnBlocked",
    "TurnComplete",
    "TurnIncomplete",
    "UIEvent",
    "UserMessagePersisted",
    # Memory
    "MemoryEntry",
    # Messages
    "Message",
    # Provider
    "MessageStop",
    "ProviderEvent",
    "ProviderRequest",
    "SystemPromptSegment",
    "TextDelta",
    "ThinkingDelta",
    "ToolCallDelta",
    "ToolCallEnd",
    "ToolCallStart",
    "ToolDefinition",
    "UsageEvent",
    # Sessions
    "Session",
]
